### ISSUE TITLE
Update to MOI v1

### ISSUE THREAD

**Issue by blegat** [dourouc05/ConstraintProgrammingExtensions.jl#31]
The release of JuMP v1.0 is quite imminent and will require MOI v1

**Comment by Wikunia** [comment]
Are there any updates on this? Just saw that my ConstraintSolver is limited to MOI v0.10 due to this repo. Did anyone try to update this yet and encountered any hurdles?

**Comment by blegat** [comment]
MOI now supports constraint programming natively, see https://github.com/jump-dev/MathOptInterface.jl/issues/1805
Is there anything missing in MOI for ConstraintSolver ?

**Comment by Wikunia** [comment]
Ah okay didn't know that. Will have to check. Thanks for the update

**Comment by blegat** [comment]
The new version v0.7 new works with MOI v1
